### ISSUE TITLE
LV2 version?

### ISSUE THREAD

**Issue by mxmilkiib** [NiklasWan/CTAG-JUCE-Sampler#2]
As there isn't really a pitch orientated [LV2](https://github.com/lv2/lv2/wiki) sampler plugin available currently, I was wondering if an LV2 version of this plugin might be possible in the future? Both the [DPF](https://github.com/DISTRHO/DPF) [JUCE](https://github.com/DISTRHO/juce) fork, and [lv2-porting-project/JUCE](https://github.com/lv2-porting-project/JUCE) (original JUCE file layout, system-wide lv2 path inludes, patched against deadlock) fork by @KottV, can build to LV2, VST2, JACK, etc.

**Comment by NiklasWan** [comment]
Hey @mxmilkiib,
sorry for the late reply.
Unfortunately there is no LV2 version of this sampler planned. It might happen though at some point in the future.

Best regards,
Niklas
